// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/album.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Albumの定義
type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_proto_album_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{0}
}

func (x *Album) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Album) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Album) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

// GetAlbumのリクエストとレスポンス
type GetAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumRequest) Reset() {
	*x = GetAlbumRequest{}
	mi := &file_proto_album_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumRequest) ProtoMessage() {}

func (x *GetAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{1}
}

func (x *GetAlbumRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *Album                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumResponse) Reset() {
	*x = GetAlbumResponse{}
	mi := &file_proto_album_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumResponse) ProtoMessage() {}

func (x *GetAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumResponse.ProtoReflect.Descriptor instead.
func (*GetAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlbumResponse) GetAlbum() *Album {
	if x != nil {
		return x.Album
	}
	return nil
}

// ListAlbumsのリクエストとレスポンス
type ListAlbumsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        string                 `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlbumsRequest) Reset() {
	*x = ListAlbumsRequest{}
	mi := &file_proto_album_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlbumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlbumsRequest) ProtoMessage() {}

func (x *ListAlbumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlbumsRequest.ProtoReflect.Descriptor instead.
func (*ListAlbumsRequest) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{3}
}

func (x *ListAlbumsRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

type ListAlbumsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *Album                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlbumsResponse) Reset() {
	*x = ListAlbumsResponse{}
	mi := &file_proto_album_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlbumsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlbumsResponse) ProtoMessage() {}

func (x *ListAlbumsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlbumsResponse.ProtoReflect.Descriptor instead.
func (*ListAlbumsResponse) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{4}
}

func (x *ListAlbumsResponse) GetAlbum() *Album {
	if x != nil {
		return x.Album
	}
	return nil
}

// GetTotalAmountのリクエストとレスポンス
type GetTotalAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalAmountRequest) Reset() {
	*x = GetTotalAmountRequest{}
	mi := &file_proto_album_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalAmountRequest) ProtoMessage() {}

func (x *GetTotalAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalAmountRequest.ProtoReflect.Descriptor instead.
func (*GetTotalAmountRequest) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{5}
}

func (x *GetTotalAmountRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetTotalAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumCount    int32                  `protobuf:"varint,1,opt,name=album_count,json=albumCount,proto3" json:"album_count,omitempty"`
	TotalAmount   float32                `protobuf:"fixed32,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalAmountResponse) Reset() {
	*x = GetTotalAmountResponse{}
	mi := &file_proto_album_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalAmountResponse) ProtoMessage() {}

func (x *GetTotalAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalAmountResponse.ProtoReflect.Descriptor instead.
func (*GetTotalAmountResponse) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{6}
}

func (x *GetTotalAmountResponse) GetAlbumCount() int32 {
	if x != nil {
		return x.AlbumCount
	}
	return 0
}

func (x *GetTotalAmountResponse) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetTotalAmountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UploadAndNotifyのリクエストとレスポンス
type UploadAndNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *Album                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAndNotifyRequest) Reset() {
	*x = UploadAndNotifyRequest{}
	mi := &file_proto_album_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAndNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAndNotifyRequest) ProtoMessage() {}

func (x *UploadAndNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAndNotifyRequest.ProtoReflect.Descriptor instead.
func (*UploadAndNotifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{7}
}

func (x *UploadAndNotifyRequest) GetAlbum() *Album {
	if x != nil {
		return x.Album
	}
	return nil
}

type UploadAndNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAndNotifyResponse) Reset() {
	*x = UploadAndNotifyResponse{}
	mi := &file_proto_album_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAndNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAndNotifyResponse) ProtoMessage() {}

func (x *UploadAndNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_album_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAndNotifyResponse.ProtoReflect.Descriptor instead.
func (*UploadAndNotifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_album_proto_rawDescGZIP(), []int{8}
}

func (x *UploadAndNotifyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_album_proto protoreflect.FileDescriptor

const file_proto_album_proto_rawDesc = "" +
	"\n" +
	"\x11proto/album.proto\x12\x05album\"K\n" +
	"\x05Album\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\"'\n" +
	"\x0fGetAlbumRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"6\n" +
	"\x10GetAlbumResponse\x12\"\n" +
	"\x05album\x18\x01 \x01(\v2\f.album.AlbumR\x05album\"+\n" +
	"\x11ListAlbumsRequest\x12\x16\n" +
	"\x06artist\x18\x01 \x01(\tR\x06artist\"8\n" +
	"\x12ListAlbumsResponse\x12\"\n" +
	"\x05album\x18\x01 \x01(\v2\f.album.AlbumR\x05album\"-\n" +
	"\x15GetTotalAmountRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"v\n" +
	"\x16GetTotalAmountResponse\x12\x1f\n" +
	"\valbum_count\x18\x01 \x01(\x05R\n" +
	"albumCount\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x02R\vtotalAmount\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"<\n" +
	"\x16UploadAndNotifyRequest\x12\"\n" +
	"\x05album\x18\x01 \x01(\v2\f.album.AlbumR\x05album\"3\n" +
	"\x17UploadAndNotifyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb7\x02\n" +
	"\fAlbumService\x12;\n" +
	"\bGetAlbum\x12\x16.album.GetAlbumRequest\x1a\x17.album.GetAlbumResponse\x12C\n" +
	"\n" +
	"ListAlbums\x12\x18.album.ListAlbumsRequest\x1a\x19.album.ListAlbumsResponse0\x01\x12O\n" +
	"\x0eGetTotalAmount\x12\x1c.album.GetTotalAmountRequest\x1a\x1d.album.GetTotalAmountResponse(\x01\x12T\n" +
	"\x0fUploadAndNotify\x12\x1d.album.UploadAndNotifyRequest\x1a\x1e.album.UploadAndNotifyResponse(\x010\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_album_proto_rawDescOnce sync.Once
	file_proto_album_proto_rawDescData []byte
)

func file_proto_album_proto_rawDescGZIP() []byte {
	file_proto_album_proto_rawDescOnce.Do(func() {
		file_proto_album_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_album_proto_rawDesc), len(file_proto_album_proto_rawDesc)))
	})
	return file_proto_album_proto_rawDescData
}

var file_proto_album_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_album_proto_goTypes = []any{
	(*Album)(nil),                   // 0: album.Album
	(*GetAlbumRequest)(nil),         // 1: album.GetAlbumRequest
	(*GetAlbumResponse)(nil),        // 2: album.GetAlbumResponse
	(*ListAlbumsRequest)(nil),       // 3: album.ListAlbumsRequest
	(*ListAlbumsResponse)(nil),      // 4: album.ListAlbumsResponse
	(*GetTotalAmountRequest)(nil),   // 5: album.GetTotalAmountRequest
	(*GetTotalAmountResponse)(nil),  // 6: album.GetTotalAmountResponse
	(*UploadAndNotifyRequest)(nil),  // 7: album.UploadAndNotifyRequest
	(*UploadAndNotifyResponse)(nil), // 8: album.UploadAndNotifyResponse
}
var file_proto_album_proto_depIdxs = []int32{
	0, // 0: album.GetAlbumResponse.album:type_name -> album.Album
	0, // 1: album.ListAlbumsResponse.album:type_name -> album.Album
	0, // 2: album.UploadAndNotifyRequest.album:type_name -> album.Album
	1, // 3: album.AlbumService.GetAlbum:input_type -> album.GetAlbumRequest
	3, // 4: album.AlbumService.ListAlbums:input_type -> album.ListAlbumsRequest
	5, // 5: album.AlbumService.GetTotalAmount:input_type -> album.GetTotalAmountRequest
	7, // 6: album.AlbumService.UploadAndNotify:input_type -> album.UploadAndNotifyRequest
	2, // 7: album.AlbumService.GetAlbum:output_type -> album.GetAlbumResponse
	4, // 8: album.AlbumService.ListAlbums:output_type -> album.ListAlbumsResponse
	6, // 9: album.AlbumService.GetTotalAmount:output_type -> album.GetTotalAmountResponse
	8, // 10: album.AlbumService.UploadAndNotify:output_type -> album.UploadAndNotifyResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_album_proto_init() }
func file_proto_album_proto_init() {
	if File_proto_album_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_album_proto_rawDesc), len(file_proto_album_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_album_proto_goTypes,
		DependencyIndexes: file_proto_album_proto_depIdxs,
		MessageInfos:      file_proto_album_proto_msgTypes,
	}.Build()
	File_proto_album_proto = out.File
	file_proto_album_proto_goTypes = nil
	file_proto_album_proto_depIdxs = nil
}
